[linux]
default:
  @echo "Usage: just <command> [options]"
  @just --choose

@clean:
  echo "Cleaning..."
  rm -rf build

@configure BUILD_TYPE="Debug":
  echo "Configuring in {{BUILD_TYPE}} mode"
  conan install . --build=missing --settings=build_type={{BUILD_TYPE}} -o "*:shared=False"

@build BUILD_TYPE="Debug" FOLDER=".":
  echo "Building in {{BUILD_TYPE}} mode"
  conan build . --output-folder={{FOLDER}} --build=missing --settings=build_type={{BUILD_TYPE}} -o "*:shared=False"
